# Generated by Django 4.2.9 on 2024-02-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='itn',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='tender_count',
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('headman', 'Headman'), ('teacher', 'Teacher')], max_length=10),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.group'),
        ),
    ]
