# Generated by Django 4.2.9 on 2024-02-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_group_remove_abstractuser_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
