# Generated by Django 4.2.9 on 2024-03-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_abstractuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
