# Generated by Django 4.2.9 on 2024-03-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_group_course_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='direction',
            field=models.CharField(default='МУИТ', max_length=35),
        ),
        migrations.AddField(
            model_name='group',
            name='stage',
            field=models.CharField(default='Бакалавриат', max_length=35),
        ),
    ]
