# Generated by Django 4.2.9 on 2024-03-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_group_direction_group_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='direction',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='group',
            name='stage',
            field=models.CharField(max_length=35),
        ),
    ]
