# Generated by Django 4.2.9 on 2024-03-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_group_direction_alter_group_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='direction',
            field=models.CharField(default='КОМТЕХНО', max_length=35),
        ),
        migrations.AlterField(
            model_name='group',
            name='stage',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
